services:
  - type: web
    name: anwar-services
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
