services:
  - type: web
    name: saraa-services
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RENDER
        value: "true"
      - key: SESSION_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_BRANCH
        value: main
      - key: PORT
        value: "10000"
